INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Landvetter', 'Gothenburg', 'SWEDEN');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Arlanda', 'Stockholm', 'SWEDEN');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Kallax', 'Lulea', 'SWEDEN');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Oslo', 'Oslo', 'Norway');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Vantaa', 'Helsinki', 'Finland');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Brandenburg', 'Berlin', 'Germany');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('Frankfurt', 'Frankfurt', 'Germany');
INSERT INTO AIRPORT (AIRPORT_NAME, AIRPORT_CITY, AIRPORT_COUNTRY) VALUES ('El Prat', 'Barcelona', 'Spain');


INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Magnus', 'Danielsson', 'mange@gmail.com', 'Delbancogatan 9A', '43135', 'Molndal', 'Sweden');
INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Abel', 'Danielsson', 'abbe@gmail.com', 'Delbancogatan 9A', '43135', 'Molndal', 'Sweden');
INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Lukas', 'Danielsson', 'lukas@gmail.com', 'Delbancogatan 9A', '43135', 'Molndal', 'Sweden');
INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Aynalem Berhanu', 'Danielsson', 'aynalem@gmail.com', 'Delbancogatan 9A', '43135', 'Molndal', 'Sweden');
INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Per', 'Danielsson', 'pelle@gmail.com', 'Solvagen 1', '12345', 'Solna', 'Sweden');
INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Gun', 'Johansson', 'gunsan@gmail.com', 'Kungsgatan 1', '56723', 'Huddinge', 'Sweden');
INSERT INTO PASSENGER (PASSENGER_FIRSTNAME, PASSENGER_LASTNAME, PASSENGER_EMAIL, PASSENGER_ADDRESS, PASSENGER_ZIPCODE, PASSENGER_CITY, PASSENGER_COUNTRY) VALUES ('Farah', 'Saleh', 'farah@gmail.com', 'Almgatan 1', '12345', 'Lysekil', 'Sweden');



